### ISSUE TITLE
can not work

### ISSUE THREAD

**Issue by grasses** [lambtron/nightmare-linkedin#5]
➜ npm install
➜ cd example
➜  examples git:(master) node crawl.js
module.js:471
    throw err;
    ^

Error: Cannot find module 'nightmare'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/homeway/Documents/null/nightmare-linkedin/examples/crawl.js:6:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by festum** [comment]
Guess it's no longer maintained.
